using System.Globalization;
using System.IO.Compression;
using System.Numerics;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using XonoticGodot.Formats.Vfs;

namespace XonoticGodot.Formats.Vmap;

/// <summary>
/// Read/write for the <c>.vmap</c> container — the package that is BOTH the editable and the shipping form of
/// a map (design doc §11.2). Two interchangeable physical layouts, same section names:
///
/// <list type="bullet">
///   <item><b>Directory</b> (<c>mymap.vmap/</c>) — what the editor writes while working; every section is a
///         separate file so a save touches only what changed and git can diff it.</item>
///   <item><b>Zip</b> (<c>mymap.vmap</c>) — the same tree packed for distribution, readable straight out of a
///         pk3 through the <see cref="VirtualFileSystem"/>.</item>
/// </list>
///
/// Sections written today (TRUTH only — the derived <c>bake/</c> cache is regenerated by
/// <see cref="VmapGeometryBuilder"/> and is not part of this container yet):
/// <code>
///   map.json        manifest: name, provenance, format version
///   geometry.json   brushes (planes + materials + texture projections) and bezier patches
///   entities.json   classnames, key/values, and which brushes/patches each brush entity owns
/// </code>
///
/// Serialization is deliberately DETERMINISTIC (fixed property order, invariant culture, round-trip floats,
/// grid-snapped values written exactly) so two saves of unchanged data are byte-identical and <c>.vmap</c>s
/// merge in git — the QoL requirement in §11.8.
/// </summary>
public static class VmapPackage
{
    public const string ManifestSection = "map.json";
    public const string GeometrySection = "geometry.json";
    public const string EntitiesSection = "entities.json";

    /// <summary>
    /// Named object sets (backlog F8). OPTIONAL, and written only when the map has any — so a package with no
    /// groups is byte-for-byte the package it always was, and an older reader still loads the map.
    /// </summary>
    public const string GroupsSection = "groups.json";

    /// <summary>
    /// Painted layer weights (backlog F2): the INDEX — id, size, resolution, projection. The texels live
    /// beside it, one deflated blob per map, because a hundred kilobytes of base64 in a JSON section would
    /// make the diffable part of the package unreadable.
    ///
    /// OPTIONAL, like the groups section: a map nobody has painted writes neither this nor a blend directory,
    /// and its bytes do not move.
    /// </summary>
    public const string BlendSection = "blend.json";

    /// <summary>Directory the per-map texel blobs live in, as <c>blend/&lt;id&gt;.bin</c>.</summary>
    public const string BlendDirectory = "blend";

    /// <summary>
    /// Format version a package needs to be READ correctly once it carries blend maps.
    ///
    /// Stamped CONDITIONALLY: an unpainted map still writes version 1 and still loads in a build without this
    /// change. Stamping it unconditionally would lock every save out of every older build — including a
    /// co-editing peer's — for a section that map does not have.
    /// </summary>
    public const int BlendFormatVersion = 2;

    /// <summary>Canonical container extension.</summary>
    public const string Extension = ".vmap";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.Never,
        NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals,
    };

    // =============================================================================================
    //  Reading
    // =============================================================================================

    /// <summary>
    /// Read a package from disk, auto-detecting the layout: a directory is read section-by-section, a file is
    /// read as a zip.
    /// </summary>
    public static VmapDocument Read(string path)
    {
        ArgumentException.ThrowIfNullOrEmpty(path);
        if (Directory.Exists(path))
            return ReadFromDirectory(path);
        if (File.Exists(path))
        {
            using FileStream fs = File.OpenRead(path);
            return ReadFromZip(fs);
        }
        throw new AssetParseException($"vmap: no package at '{path}'");
    }

    /// <summary>Read a package laid out as a directory of section files.</summary>
    public static VmapDocument ReadFromDirectory(string dir)
    {
        ArgumentException.ThrowIfNullOrEmpty(dir);
        return Assemble(
            ReadTextFile(Path.Combine(dir, ManifestSection), required: true)!,
            ReadTextFile(Path.Combine(dir, GeometrySection), required: false),
            ReadTextFile(Path.Combine(dir, EntitiesSection), required: false),
            ReadTextFile(Path.Combine(dir, GroupsSection), required: false),
            name => ReadBinaryFile(Path.Combine(dir, name)));
    }

    /// <summary>Read a package from a zip stream (the shipping layout).</summary>
    public static VmapDocument ReadFromZip(Stream zip)
    {
        ArgumentNullException.ThrowIfNull(zip);
        using var archive = new ZipArchive(zip, ZipArchiveMode.Read, leaveOpen: true);
        return Assemble(
            ReadZipEntry(archive, ManifestSection, required: true)!,
            ReadZipEntry(archive, GeometrySection, required: false),
            ReadZipEntry(archive, EntitiesSection, required: false),
            ReadZipEntry(archive, GroupsSection, required: false),
            name => ReadZipBytes(archive, name));
    }

    /// <summary>
    /// Read a packaged <c>.vmap</c> through the virtual file system, so shipped maps can live inside a pk3
    /// exactly like a <c>.bsp</c> does.
    /// </summary>
    public static VmapDocument ReadFromVfs(VirtualFileSystem vfs, string vpath)
    {
        ArgumentNullException.ThrowIfNull(vfs);
        ArgumentException.ThrowIfNullOrEmpty(vpath);
        byte[] bytes = vfs.ReadBytes(vpath);
        using var ms = new MemoryStream(bytes, writable: false);
        return ReadFromZip(ms);
    }

    private static string? ReadTextFile(string path, bool required)
    {
        if (File.Exists(path))
            return File.ReadAllText(path, Encoding.UTF8);
        if (required)
            throw new AssetParseException($"vmap: missing required section '{Path.GetFileName(path)}' in '{Path.GetDirectoryName(path)}'");
        return null;
    }

    private static string? ReadZipEntry(ZipArchive archive, string name, bool required)
    {
        ZipArchiveEntry? entry = archive.GetEntry(name);
        if (entry is null)
        {
            if (required)
                throw new AssetParseException($"vmap: missing required section '{name}' in package");
            return null;
        }
        using Stream s = entry.Open();
        using var reader = new StreamReader(s, Encoding.UTF8);
        return reader.ReadToEnd();
    }

    private static VmapDocument Assemble(
        string manifestJson, string? geometryJson, string? entitiesJson, string? groupsJson = null,
        Func<string, byte[]?>? readBinary = null)
    {
        var doc = new VmapDocument();

        ManifestDto manifest = Deserialize<ManifestDto>(manifestJson, ManifestSection);
        doc.FormatVersion = manifest.FormatVersion;
        if (doc.FormatVersion > VmapDocument.CurrentFormatVersion)
            throw new AssetParseException(
                $"vmap: package format version {doc.FormatVersion} is newer than this build supports ({VmapDocument.CurrentFormatVersion})");
        doc.Manifest = new VmapManifest
        {
            Name = manifest.Name ?? string.Empty,
            Title = manifest.Title ?? string.Empty,
            SourceKind = manifest.SourceKind ?? string.Empty,
            SourcePath = manifest.SourcePath ?? string.Empty,
            SourceHash = manifest.SourceHash ?? string.Empty,
        };

        if (readBinary is not null && readBinary(BlendSection) is { } blendIndexBytes)
        {
            BlendIndexDto index = Deserialize<BlendIndexDto>(
                Encoding.UTF8.GetString(blendIndexBytes), BlendSection);
            foreach (BlendMapDto b in index.Maps ?? Array.Empty<BlendMapDto>())
            {
                if (b.Width <= 0 || b.Height <= 0)
                    continue;
                byte[]? packed = readBinary($"{BlendDirectory}/{b.Id}.bin");
                if (packed is null)
                    continue;

                byte[] texels = Inflate(packed, b.Width * b.Height * 4);
                if (texels.Length != b.Width * b.Height * 4)
                    continue;   // a blob that disagrees with its index entry is not a blend map

                doc.BlendMaps.Add(new VmapBlendMap
                {
                    Id = b.Id,
                    Width = b.Width,
                    Height = b.Height,
                    UnitsPerTexel = b.UnitsPerTexel <= 0f ? 4f : b.UnitsPerTexel,
                    Projection = new VmapTexProjection(
                        Vec3(b.AxisU), Vec3(b.AxisV), b.OffsetU, b.OffsetV),
                    Texels = texels,
                });
            }
        }

        if (groupsJson is not null)
        {
            GroupsDto groups = Deserialize<GroupsDto>(groupsJson, GroupsSection);
            foreach (GroupDto g in groups.Groups ?? Array.Empty<GroupDto>())
                doc.Groups.Add(
                    new VmapGroup { Id = g.Id, Name = g.Name ?? string.Empty, Hidden = g.Hidden });
        }

        if (geometryJson is not null)
        {
            GeometryDto geo = Deserialize<GeometryDto>(geometryJson, GeometrySection);
            foreach (BrushDto b in geo.Brushes ?? Array.Empty<BrushDto>())
            {
                var brush = new VmapBrush
                {
                    Id = b.Id, IsDetail = b.Detail, ContentFlags = b.Contents, GroupId = b.Group,
                };
                foreach (FaceDto f in b.Faces ?? Array.Empty<FaceDto>())
                {
                    // The flat fields ARE the base layer, so a package written before layers existed reads
                    // back as a one-layer face with no special case.
                    var face = new VmapFace
                    {
                        BlendMapId = f.BlendMap,
                        Plane = new VmapPlane(Vec3(f.Normal), f.Dist),
                        Material = f.Material ?? string.Empty,
                        Projection = new VmapTexProjection(Vec3(f.AxisU), Vec3(f.AxisV), f.OffsetU, f.OffsetV),
                        SurfaceFlags = f.Surface,
                        ContentFlags = f.Contents,
                    };
                    foreach (LayerDto l in f.ExtraLayers ?? Array.Empty<LayerDto>())
                    {
                        face.Layers.Add(new VmapFaceLayer
                        {
                            Material = l.Material ?? string.Empty,
                            Projection = new VmapTexProjection(
                                Vec3(l.AxisU), Vec3(l.AxisV), l.OffsetU, l.OffsetV),
                            Blend = (VmapBlend)l.Blend,
                            WeightChannel = l.WeightChannel,
                        });
                    }
                    brush.Faces.Add(face);
                }
                doc.Brushes.Add(brush);
            }

            foreach (PatchDto p in geo.Patches ?? Array.Empty<PatchDto>())
            {
                var patch = new VmapPatch
                {
                    Id = p.Id,
                    Material = p.Material ?? string.Empty,
                    Width = p.Width,
                    Height = p.Height,
                    SurfaceFlags = p.Surface,
                    ContentFlags = p.Contents,
                    GroupId = p.Group,
                };
                float[] ctrl = p.Controls ?? Array.Empty<float>();
                for (int i = 0; i + 2 < ctrl.Length; i += 3)
                    patch.Controls.Add(new Vector3(ctrl[i], ctrl[i + 1], ctrl[i + 2]));
                float[] uvs = p.Uvs ?? Array.Empty<float>();
                for (int i = 0; i + 1 < uvs.Length; i += 2)
                    patch.ControlUvs.Add(new Vector2(uvs[i], uvs[i + 1]));
                doc.Patches.Add(patch);
            }
        }

        if (entitiesJson is not null)
        {
            EntitiesDto ents = Deserialize<EntitiesDto>(entitiesJson, EntitiesSection);
            foreach (EntityDto e in ents.Entities ?? Array.Empty<EntityDto>())
            {
                var ent = new VmapEntity
                {
                    Id = e.Id, ClassName = e.ClassName ?? string.Empty, GroupId = e.Group,
                };
                foreach (KeyValuePair<string, string> kv in e.Fields ?? new Dictionary<string, string>())
                    ent.Fields[kv.Key] = kv.Value;
                if (!string.IsNullOrEmpty(ent.ClassName))
                    ent.Fields["classname"] = ent.ClassName;
                ent.BrushIds.AddRange(e.Brushes ?? Array.Empty<int>());
                ent.PatchIds.AddRange(e.Patches ?? Array.Empty<int>());
                doc.Entities.Add(ent);
            }
        }

        return doc;
    }

    private static T Deserialize<T>(string json, string section)
    {
        try
        {
            return JsonSerializer.Deserialize<T>(json, JsonOptions)
                   ?? throw new AssetParseException($"vmap: section '{section}' deserialized to null");
        }
        catch (JsonException ex)
        {
            throw new AssetParseException($"vmap: malformed section '{section}': {ex.Message}", ex);
        }
    }

    private static Vector3 Vec3(float[]? a)
        => a is { Length: >= 3 } ? new Vector3(a[0], a[1], a[2]) : Vector3.Zero;

    // =============================================================================================
    //  Writing
    // =============================================================================================

    /// <summary>Write the package as a directory of section files (the editor's working layout).</summary>
    public static void WriteToDirectory(VmapDocument doc, string dir)
    {
        ArgumentNullException.ThrowIfNull(doc);
        ArgumentException.ThrowIfNullOrEmpty(dir);
        Directory.CreateDirectory(dir);

        // Serialize everything BEFORE touching the existing save. A document that throws part-way through —
        // and the geometry writer walks every brush, so it can — would otherwise have already replaced the
        // manifest, leaving a package whose sections describe different maps.
        string manifest = SerializeManifest(doc);
        string? blendIndex = SerializeBlendIndex(doc);
        string geometry = SerializeGeometry(doc);
        string entities = SerializeEntities(doc);
        string? groups = SerializeGroups(doc);

        // Written beside the real files and moved into place, rather than written over them. The three
        // sections are one document: a process that dies between the second and third write would leave new
        // geometry against old entities, and the mapper would not find out until the next load. Autosave makes
        // that likelier, not less — it runs unattended, on a timer, while the editor is doing other things.
        WriteAtomic(Path.Combine(dir, ManifestSection), manifest);
        WriteAtomic(Path.Combine(dir, GeometrySection), geometry);
        WriteAtomic(Path.Combine(dir, EntitiesSection), entities);

        // Written only when there ARE groups, and REMOVED when the last one goes: a stale groups.json
        // naming sets that nothing belongs to any more would be read straight back on the next load.
        string groupsPath = Path.Combine(dir, GroupsSection);
        if (groups is not null)
            WriteAtomic(groupsPath, groups);
        else if (File.Exists(groupsPath))
            File.Delete(groupsPath);

        // Same rule for the paint: written only when there is some, and cleared out when there is not, so a
        // stale index cannot name maps no face refers to any more.
        string blendPath = Path.Combine(dir, BlendSection);
        string blendDir = Path.Combine(dir, BlendDirectory);
        if (blendIndex is not null)
        {
            WriteAtomic(blendPath, blendIndex);
            Directory.CreateDirectory(blendDir);
            foreach (VmapBlendMap m in doc.BlendMaps)
                if (m.IsValid)
                    WriteAtomicBytes(Path.Combine(blendDir, $"{m.Id}.bin"), Deflate(m.Texels));
        }
        else
        {
            if (File.Exists(blendPath))
                File.Delete(blendPath);
            if (Directory.Exists(blendDir))
                Directory.Delete(blendDir, recursive: true);
        }
    }

    /// <summary>
    /// Write a file by way of a sibling temporary, so an interrupted write cannot leave a half-written section
    /// where a readable one used to be. The move is same-directory, which is where a filesystem rename is
    /// cheapest and closest to atomic.
    /// </summary>
    private static void WriteAtomic(string path, string content)
    {
        string tmp = path + ".tmp";
        File.WriteAllText(tmp, content, Utf8NoBom);
        File.Move(tmp, path, overwrite: true);
    }

    /// <summary>Write the package as a single zip file (the shipping layout).</summary>
    public static void WriteToZip(VmapDocument doc, string path)
    {
        ArgumentNullException.ThrowIfNull(doc);
        ArgumentException.ThrowIfNullOrEmpty(path);
        string? parent = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(parent))
            Directory.CreateDirectory(parent);
        using FileStream fs = File.Create(path);
        using var archive = new ZipArchive(fs, ZipArchiveMode.Create);
        WriteZipEntry(archive, ManifestSection, SerializeManifest(doc));
        WriteZipEntry(archive, GeometrySection, SerializeGeometry(doc));
        WriteZipEntry(archive, EntitiesSection, SerializeEntities(doc));
        if (SerializeGroups(doc) is { } groups)
            WriteZipEntry(archive, GroupsSection, groups);
        if (SerializeBlendIndex(doc) is { } blendIndex)
        {
            WriteZipEntry(archive, BlendSection, blendIndex);
            foreach (VmapBlendMap m in doc.BlendMaps)
                if (m.IsValid)
                    WriteZipBytes(archive, $"{BlendDirectory}/{m.Id}.bin", Deflate(m.Texels));
        }
    }

    private static byte[]? ReadBinaryFile(string path)
        => File.Exists(path) ? File.ReadAllBytes(path) : null;

    private static byte[]? ReadZipBytes(ZipArchive archive, string name)
    {
        ZipArchiveEntry? entry = archive.GetEntry(name);
        if (entry is null)
            return null;
        using Stream s = entry.Open();
        using var ms = new MemoryStream();
        s.CopyTo(ms);
        return ms.ToArray();
    }

    private static void WriteZipBytes(ZipArchive archive, string name, byte[] bytes)
    {
        using Stream s = archive.CreateEntry(name, CompressionLevel.Optimal).Open();
        s.Write(bytes, 0, bytes.Length);
    }

    private static void WriteAtomicBytes(string path, byte[] bytes)
    {
        string tmp = path + ".tmp";
        File.WriteAllBytes(tmp, bytes);
        File.Move(tmp, path, overwrite: true);
    }

    /// <summary>
    /// Deflate a texel buffer. A blend map is mostly zeroes until it is painted and mostly flat where it is,
    /// so this runs 50-100x — which is what keeps a painted face around a kilobyte on disk.
    /// </summary>
    private static byte[] Deflate(byte[] raw)
    {
        using var ms = new MemoryStream();
        using (var gz = new DeflateStream(ms, CompressionLevel.Optimal, leaveOpen: true))
            gz.Write(raw, 0, raw.Length);
        return ms.ToArray();
    }

    /// <param name="expected">
    /// Bytes the index says this map has. A ceiling as much as a hint: without it a hostile blob could inflate
    /// without bound into memory.
    /// </param>
    private static byte[] Inflate(byte[] packed, int expected)
    {
        if (expected <= 0 || expected > 64 * 1024 * 1024)
            return Array.Empty<byte>();
        try
        {
            var result = new byte[expected];
            using var ms = new MemoryStream(packed, writable: false);
            using var gz = new DeflateStream(ms, CompressionMode.Decompress);
            int read = 0;
            while (read < expected)
            {
                int n = gz.Read(result, read, expected - read);
                if (n <= 0)
                    break;
                read += n;
            }
            return read == expected ? result : Array.Empty<byte>();
        }
        catch (InvalidDataException)
        {
            return Array.Empty<byte>();
        }
    }

    private static readonly UTF8Encoding Utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);

    private static void WriteZipEntry(ZipArchive archive, string name, string content)
    {
        ZipArchiveEntry entry = archive.CreateEntry(name, CompressionLevel.Optimal);
        using Stream s = entry.Open();
        using var writer = new StreamWriter(s, Utf8NoBom);
        writer.Write(content);
    }

    private static string SerializeManifest(VmapDocument doc)
        => JsonSerializer.Serialize(new ManifestDto
        {
            // CONDITIONAL: a map with no paint keeps writing version 1, so it still loads in a build
            // without blend maps — including a co-editing peer's.
            FormatVersion = doc.BlendMaps.Count > 0 ? BlendFormatVersion : 1,
            Name = doc.Manifest.Name,
            Title = doc.Manifest.Title,
            SourceKind = doc.Manifest.SourceKind,
            SourcePath = doc.Manifest.SourcePath,
            SourceHash = doc.Manifest.SourceHash,
        }, JsonOptions);

    private static string SerializeGeometry(VmapDocument doc)
    {
        var geo = new GeometryDto
        {
            Brushes = new BrushDto[doc.Brushes.Count],
            Patches = new PatchDto[doc.Patches.Count],
        };

        for (int i = 0; i < doc.Brushes.Count; i++)
        {
            VmapBrush b = doc.Brushes[i];
            var faces = new FaceDto[b.Faces.Count];
            for (int f = 0; f < b.Faces.Count; f++)
            {
                VmapFace face = b.Faces[f];
                faces[f] = new FaceDto
                {
                    Normal = Arr(face.Plane.Normal),
                    Dist = face.Plane.Dist,
                    Material = face.Material,
                    AxisU = Arr(face.Projection.AxisU),
                    AxisV = Arr(face.Projection.AxisV),
                    OffsetU = face.Projection.OffsetU,
                    OffsetV = face.Projection.OffsetV,
                    Surface = face.SurfaceFlags,
                    Contents = face.ContentFlags,
                    BlendMap = face.BlendMapId,

                    // Only the layers ABOVE the base, and omitted entirely when there are none. The base stays
                    // in the flat fields above, so a single-layer face writes exactly the bytes it always did:
                    // existing packages do not churn, older readers still get the map, and a diff of a
                    // layered face shows only the layers.
                    ExtraLayers = face.Layers.Count > 1 ? LayerDtos(face) : null,
                };
            }
            geo.Brushes[i] = new BrushDto
            {
                Id = b.Id,
                Detail = b.IsDetail,
                Contents = b.ContentFlags,
                Group = b.GroupId,
                Faces = faces,
            };
        }

        for (int i = 0; i < doc.Patches.Count; i++)
        {
            VmapPatch p = doc.Patches[i];
            var ctrl = new float[p.Controls.Count * 3];
            for (int c = 0; c < p.Controls.Count; c++)
            {
                ctrl[c * 3 + 0] = p.Controls[c].X;
                ctrl[c * 3 + 1] = p.Controls[c].Y;
                ctrl[c * 3 + 2] = p.Controls[c].Z;
            }
            var uvs = new float[p.ControlUvs.Count * 2];
            for (int c = 0; c < p.ControlUvs.Count; c++)
            {
                uvs[c * 2 + 0] = p.ControlUvs[c].X;
                uvs[c * 2 + 1] = p.ControlUvs[c].Y;
            }
            geo.Patches[i] = new PatchDto
            {
                Id = p.Id,
                Material = p.Material,
                Width = p.Width,
                Height = p.Height,
                Surface = p.SurfaceFlags,
                Contents = p.ContentFlags,
                Group = p.GroupId,
                Controls = ctrl,
                Uvs = uvs,
            };
        }

        return JsonSerializer.Serialize(geo, JsonOptions);
    }

    private static string SerializeEntities(VmapDocument doc)
    {
        var dto = new EntitiesDto { Entities = new EntityDto[doc.Entities.Count] };
        for (int i = 0; i < doc.Entities.Count; i++)
        {
            VmapEntity e = doc.Entities[i];

            // Deterministic key order so unchanged data round-trips byte-identically (§11.8 diff-friendliness).
            var fields = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (string key in e.Fields.Keys.OrderBy(k => k, StringComparer.Ordinal))
                fields[key] = e.Fields[key];

            dto.Entities[i] = new EntityDto
            {
                Id = e.Id,
                ClassName = e.ClassName,
                Fields = fields,
                Brushes = e.BrushIds.ToArray(),
                Patches = e.PatchIds.ToArray(),
                Group = e.GroupId,
            };
        }
        return JsonSerializer.Serialize(dto, JsonOptions);
    }

    /// <summary>
    /// The blend INDEX, or null when nothing is painted — in which case neither it nor the texel blobs are
    /// written.
    /// </summary>
    private static string? SerializeBlendIndex(VmapDocument doc)
    {
        var maps = new List<BlendMapDto>(doc.BlendMaps.Count);
        foreach (VmapBlendMap m in doc.BlendMaps)
        {
            if (!m.IsValid)
                continue;
            maps.Add(new BlendMapDto
            {
                Id = m.Id,
                Width = m.Width,
                Height = m.Height,
                UnitsPerTexel = m.UnitsPerTexel,
                AxisU = Arr(m.Projection.AxisU),
                AxisV = Arr(m.Projection.AxisV),
                OffsetU = m.Projection.OffsetU,
                OffsetV = m.Projection.OffsetV,
            });
        }
        return maps.Count == 0
            ? null
            : JsonSerializer.Serialize(new BlendIndexDto { Maps = maps.ToArray() }, JsonOptions);
    }

    /// <summary>
    /// The groups section, or null when the map has none — in which case it is not written at all.
    /// </summary>
    private static string? SerializeGroups(VmapDocument doc)
    {
        if (doc.Groups.Count == 0)
            return null;

        var dto = new GroupsDto { Groups = new GroupDto[doc.Groups.Count] };
        for (int i = 0; i < doc.Groups.Count; i++)
        {
            VmapGroup g = doc.Groups[i];
            dto.Groups[i] = new GroupDto { Id = g.Id, Name = g.Name, Hidden = g.Hidden };
        }
        return JsonSerializer.Serialize(dto, JsonOptions);
    }

    private static float[] Arr(Vector3 v) => new[] { v.X, v.Y, v.Z };

    /// <summary>
    /// Content hash of arbitrary source bytes (FNV-1a 64), used to stamp <see cref="VmapManifest.SourceHash"/>
    /// so a bake cache can be keyed to the geometry it was built from and a redundant re-import is detectable.
    /// Not cryptographic — it only has to notice that bytes changed.
    /// </summary>
    public static string HashBytes(ReadOnlySpan<byte> data)
    {
        const ulong offset = 14695981039346656037UL;
        const ulong prime = 1099511628211UL;
        ulong h = offset;
        foreach (byte b in data)
        {
            h ^= b;
            h *= prime;
        }
        return h.ToString("x16", CultureInfo.InvariantCulture);
    }

    // =============================================================================================
    //  On-disk DTOs — the wire shape, deliberately decoupled from the domain model so refactoring
    //  VmapDocument does not silently change the file format. Property order here IS the file order.
    // =============================================================================================

    private sealed class ManifestDto
    {
        [JsonPropertyName("formatVersion")] public int FormatVersion { get; set; }
        [JsonPropertyName("name")] public string? Name { get; set; }
        [JsonPropertyName("title")] public string? Title { get; set; }
        [JsonPropertyName("sourceKind")] public string? SourceKind { get; set; }
        [JsonPropertyName("sourcePath")] public string? SourcePath { get; set; }
        [JsonPropertyName("sourceHash")] public string? SourceHash { get; set; }
    }

    private sealed class GeometryDto
    {
        [JsonPropertyName("brushes")] public BrushDto[]? Brushes { get; set; }
        [JsonPropertyName("patches")] public PatchDto[]? Patches { get; set; }
    }

    private sealed class BrushDto
    {
        [JsonPropertyName("id")] public int Id { get; set; }
        [JsonPropertyName("detail")] public bool Detail { get; set; }
        [JsonPropertyName("contents")] public int Contents { get; set; }
        [JsonPropertyName("faces")] public FaceDto[]? Faces { get; set; }

        /// <summary>
        /// Group membership (backlog F8). Omitted when 0, which is every object on every map that has no
        /// groups, so no existing package changes a byte on its next save.
        /// </summary>
        [JsonPropertyName("group")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public int Group { get; set; }
    }

    private sealed class FaceDto
    {
        [JsonPropertyName("normal")] public float[]? Normal { get; set; }
        [JsonPropertyName("dist")] public float Dist { get; set; }
        [JsonPropertyName("material")] public string? Material { get; set; }
        [JsonPropertyName("axisU")] public float[]? AxisU { get; set; }
        [JsonPropertyName("axisV")] public float[]? AxisV { get; set; }
        [JsonPropertyName("offsetU")] public float OffsetU { get; set; }
        [JsonPropertyName("offsetV")] public float OffsetV { get; set; }
        [JsonPropertyName("surface")] public int Surface { get; set; }
        [JsonPropertyName("contents")] public int Contents { get; set; }

        /// <summary>
        /// The face's painted weight map (backlog F2). Omitted when 0, so an unpainted face writes what it
        /// always did.
        /// </summary>
        [JsonPropertyName("blendMap")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public int BlendMap { get; set; }

        /// <summary>
        /// Layers ABOVE the base one, which lives in the flat fields above. Omitted entirely on a plain face —
        /// not written as null — so a single-layer face is byte-for-byte what it was before layers existed and
        /// no package in the wild churns on its next save.
        /// </summary>
        [JsonPropertyName("extraLayers")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public LayerDto[]? ExtraLayers { get; set; }
    }

    private sealed class LayerDto
    {
        [JsonPropertyName("material")] public string? Material { get; set; }
        [JsonPropertyName("axisU")] public float[]? AxisU { get; set; }
        [JsonPropertyName("axisV")] public float[]? AxisV { get; set; }
        [JsonPropertyName("offsetU")] public float OffsetU { get; set; }
        [JsonPropertyName("offsetV")] public float OffsetV { get; set; }
        [JsonPropertyName("blend")] public int Blend { get; set; }
        [JsonPropertyName("weightChannel")] public int WeightChannel { get; set; }
    }

    private static LayerDto[] LayerDtos(VmapFace face)
    {
        var dtos = new LayerDto[face.Layers.Count - 1];
        for (int i = 1; i < face.Layers.Count; i++)
        {
            VmapFaceLayer l = face.Layers[i];
            dtos[i - 1] = new LayerDto
            {
                Material = l.Material,
                AxisU = Arr(l.Projection.AxisU),
                AxisV = Arr(l.Projection.AxisV),
                OffsetU = l.Projection.OffsetU,
                OffsetV = l.Projection.OffsetV,
                Blend = (int)l.Blend,
                WeightChannel = l.WeightChannel,
            };
        }
        return dtos;
    }

    private sealed class PatchDto
    {
        [JsonPropertyName("id")] public int Id { get; set; }
        [JsonPropertyName("material")] public string? Material { get; set; }
        [JsonPropertyName("width")] public int Width { get; set; }
        [JsonPropertyName("height")] public int Height { get; set; }
        [JsonPropertyName("surface")] public int Surface { get; set; }
        [JsonPropertyName("contents")] public int Contents { get; set; }
        [JsonPropertyName("controls")] public float[]? Controls { get; set; }
        [JsonPropertyName("uvs")] public float[]? Uvs { get; set; }

        /// <summary>
        /// Group membership (backlog F8). Omitted when 0, which is every object on every map that has no
        /// groups, so no existing package changes a byte on its next save.
        /// </summary>
        [JsonPropertyName("group")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public int Group { get; set; }
    }

    private sealed class EntitiesDto
    {
        [JsonPropertyName("entities")] public EntityDto[]? Entities { get; set; }
    }

    private sealed class EntityDto
    {
        [JsonPropertyName("id")] public int Id { get; set; }
        [JsonPropertyName("classname")] public string? ClassName { get; set; }
        [JsonPropertyName("fields")] public Dictionary<string, string>? Fields { get; set; }
        [JsonPropertyName("brushes")] public int[]? Brushes { get; set; }
        [JsonPropertyName("patches")] public int[]? Patches { get; set; }

        /// <summary>
        /// Group membership (backlog F8). Omitted when 0, which is every object on every map that has no
        /// groups, so no existing package changes a byte on its next save.
        /// </summary>
        [JsonPropertyName("group")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public int Group { get; set; }
    }

    private sealed class BlendIndexDto
    {
        [JsonPropertyName("maps")] public BlendMapDto[]? Maps { get; set; }
    }

    private sealed class BlendMapDto
    {
        [JsonPropertyName("id")] public int Id { get; set; }
        [JsonPropertyName("width")] public int Width { get; set; }
        [JsonPropertyName("height")] public int Height { get; set; }
        [JsonPropertyName("unitsPerTexel")] public float UnitsPerTexel { get; set; }
        [JsonPropertyName("axisU")] public float[]? AxisU { get; set; }
        [JsonPropertyName("axisV")] public float[]? AxisV { get; set; }
        [JsonPropertyName("offsetU")] public float OffsetU { get; set; }
        [JsonPropertyName("offsetV")] public float OffsetV { get; set; }
    }

    private sealed class GroupsDto
    {
        [JsonPropertyName("groups")] public GroupDto[]? Groups { get; set; }
    }

    private sealed class GroupDto
    {
        [JsonPropertyName("id")] public int Id { get; set; }
        [JsonPropertyName("name")] public string? Name { get; set; }
        [JsonPropertyName("hidden")] public bool Hidden { get; set; }
    }
}
