using System.Globalization;
using System.IO.Compression;
using System.Numerics;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using XonoticGodot.Formats.Vfs;

namespace XonoticGodot.Formats.Vmap;

/// <summary>
/// Read/write for the <c>.vmap</c> container — the package that is BOTH the editable and the shipping form of
/// a map (design doc §11.2). Two interchangeable physical layouts, same section names:
///
/// <list type="bullet">
///   <item><b>Directory</b> (<c>mymap.vmap/</c>) — what the editor writes while working; every section is a
///         separate file so a save touches only what changed and git can diff it.</item>
///   <item><b>Zip</b> (<c>mymap.vmap</c>) — the same tree packed for distribution, readable straight out of a
///         pk3 through the <see cref="VirtualFileSystem"/>.</item>
/// </list>
///
/// Sections written today (TRUTH only — the derived <c>bake/</c> cache is regenerated by
/// <see cref="VmapGeometryBuilder"/> and is not part of this container yet):
/// <code>
///   map.json        manifest: name, provenance, format version
///   geometry.json   brushes (planes + materials + texture projections) and bezier patches
///   entities.json   classnames, key/values, and which brushes/patches each brush entity owns
/// </code>
///
/// Serialization is deliberately DETERMINISTIC (fixed property order, invariant culture, round-trip floats,
/// grid-snapped values written exactly) so two saves of unchanged data are byte-identical and <c>.vmap</c>s
/// merge in git — the QoL requirement in §11.8.
/// </summary>
public static class VmapPackage
{
    public const string ManifestSection = "map.json";
    public const string GeometrySection = "geometry.json";
    public const string EntitiesSection = "entities.json";

    /// <summary>Canonical container extension.</summary>
    public const string Extension = ".vmap";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.Never,
        NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals,
    };

    // =============================================================================================
    //  Reading
    // =============================================================================================

    /// <summary>
    /// Read a package from disk, auto-detecting the layout: a directory is read section-by-section, a file is
    /// read as a zip.
    /// </summary>
    public static VmapDocument Read(string path)
    {
        ArgumentException.ThrowIfNullOrEmpty(path);
        if (Directory.Exists(path))
            return ReadFromDirectory(path);
        if (File.Exists(path))
        {
            using FileStream fs = File.OpenRead(path);
            return ReadFromZip(fs);
        }
        throw new AssetParseException($"vmap: no package at '{path}'");
    }

    /// <summary>Read a package laid out as a directory of section files.</summary>
    public static VmapDocument ReadFromDirectory(string dir)
    {
        ArgumentException.ThrowIfNullOrEmpty(dir);
        return Assemble(
            ReadTextFile(Path.Combine(dir, ManifestSection), required: true)!,
            ReadTextFile(Path.Combine(dir, GeometrySection), required: false),
            ReadTextFile(Path.Combine(dir, EntitiesSection), required: false));
    }

    /// <summary>Read a package from a zip stream (the shipping layout).</summary>
    public static VmapDocument ReadFromZip(Stream zip)
    {
        ArgumentNullException.ThrowIfNull(zip);
        using var archive = new ZipArchive(zip, ZipArchiveMode.Read, leaveOpen: true);
        return Assemble(
            ReadZipEntry(archive, ManifestSection, required: true)!,
            ReadZipEntry(archive, GeometrySection, required: false),
            ReadZipEntry(archive, EntitiesSection, required: false));
    }

    /// <summary>
    /// Read a packaged <c>.vmap</c> through the virtual file system, so shipped maps can live inside a pk3
    /// exactly like a <c>.bsp</c> does.
    /// </summary>
    public static VmapDocument ReadFromVfs(VirtualFileSystem vfs, string vpath)
    {
        ArgumentNullException.ThrowIfNull(vfs);
        ArgumentException.ThrowIfNullOrEmpty(vpath);
        byte[] bytes = vfs.ReadBytes(vpath);
        using var ms = new MemoryStream(bytes, writable: false);
        return ReadFromZip(ms);
    }

    private static string? ReadTextFile(string path, bool required)
    {
        if (File.Exists(path))
            return File.ReadAllText(path, Encoding.UTF8);
        if (required)
            throw new AssetParseException($"vmap: missing required section '{Path.GetFileName(path)}' in '{Path.GetDirectoryName(path)}'");
        return null;
    }

    private static string? ReadZipEntry(ZipArchive archive, string name, bool required)
    {
        ZipArchiveEntry? entry = archive.GetEntry(name);
        if (entry is null)
        {
            if (required)
                throw new AssetParseException($"vmap: missing required section '{name}' in package");
            return null;
        }
        using Stream s = entry.Open();
        using var reader = new StreamReader(s, Encoding.UTF8);
        return reader.ReadToEnd();
    }

    private static VmapDocument Assemble(string manifestJson, string? geometryJson, string? entitiesJson)
    {
        var doc = new VmapDocument();

        ManifestDto manifest = Deserialize<ManifestDto>(manifestJson, ManifestSection);
        doc.FormatVersion = manifest.FormatVersion;
        if (doc.FormatVersion > VmapDocument.CurrentFormatVersion)
            throw new AssetParseException(
                $"vmap: package format version {doc.FormatVersion} is newer than this build supports ({VmapDocument.CurrentFormatVersion})");
        doc.Manifest = new VmapManifest
        {
            Name = manifest.Name ?? string.Empty,
            Title = manifest.Title ?? string.Empty,
            SourceKind = manifest.SourceKind ?? string.Empty,
            SourcePath = manifest.SourcePath ?? string.Empty,
            SourceHash = manifest.SourceHash ?? string.Empty,
        };

        if (geometryJson is not null)
        {
            GeometryDto geo = Deserialize<GeometryDto>(geometryJson, GeometrySection);
            foreach (BrushDto b in geo.Brushes ?? Array.Empty<BrushDto>())
            {
                var brush = new VmapBrush { Id = b.Id, IsDetail = b.Detail, ContentFlags = b.Contents };
                foreach (FaceDto f in b.Faces ?? Array.Empty<FaceDto>())
                {
                    brush.Faces.Add(new VmapFace
                    {
                        Plane = new VmapPlane(Vec3(f.Normal), f.Dist),
                        Material = f.Material ?? string.Empty,
                        Projection = new VmapTexProjection(Vec3(f.AxisU), Vec3(f.AxisV), f.OffsetU, f.OffsetV),
                        SurfaceFlags = f.Surface,
                        ContentFlags = f.Contents,
                    });
                }
                doc.Brushes.Add(brush);
            }

            foreach (PatchDto p in geo.Patches ?? Array.Empty<PatchDto>())
            {
                var patch = new VmapPatch
                {
                    Id = p.Id,
                    Material = p.Material ?? string.Empty,
                    Width = p.Width,
                    Height = p.Height,
                    SurfaceFlags = p.Surface,
                    ContentFlags = p.Contents,
                };
                float[] ctrl = p.Controls ?? Array.Empty<float>();
                for (int i = 0; i + 2 < ctrl.Length; i += 3)
                    patch.Controls.Add(new Vector3(ctrl[i], ctrl[i + 1], ctrl[i + 2]));
                float[] uvs = p.Uvs ?? Array.Empty<float>();
                for (int i = 0; i + 1 < uvs.Length; i += 2)
                    patch.ControlUvs.Add(new Vector2(uvs[i], uvs[i + 1]));
                doc.Patches.Add(patch);
            }
        }

        if (entitiesJson is not null)
        {
            EntitiesDto ents = Deserialize<EntitiesDto>(entitiesJson, EntitiesSection);
            foreach (EntityDto e in ents.Entities ?? Array.Empty<EntityDto>())
            {
                var ent = new VmapEntity { Id = e.Id, ClassName = e.ClassName ?? string.Empty };
                foreach (KeyValuePair<string, string> kv in e.Fields ?? new Dictionary<string, string>())
                    ent.Fields[kv.Key] = kv.Value;
                if (!string.IsNullOrEmpty(ent.ClassName))
                    ent.Fields["classname"] = ent.ClassName;
                ent.BrushIds.AddRange(e.Brushes ?? Array.Empty<int>());
                ent.PatchIds.AddRange(e.Patches ?? Array.Empty<int>());
                doc.Entities.Add(ent);
            }
        }

        return doc;
    }

    private static T Deserialize<T>(string json, string section)
    {
        try
        {
            return JsonSerializer.Deserialize<T>(json, JsonOptions)
                   ?? throw new AssetParseException($"vmap: section '{section}' deserialized to null");
        }
        catch (JsonException ex)
        {
            throw new AssetParseException($"vmap: malformed section '{section}': {ex.Message}", ex);
        }
    }

    private static Vector3 Vec3(float[]? a)
        => a is { Length: >= 3 } ? new Vector3(a[0], a[1], a[2]) : Vector3.Zero;

    // =============================================================================================
    //  Writing
    // =============================================================================================

    /// <summary>Write the package as a directory of section files (the editor's working layout).</summary>
    public static void WriteToDirectory(VmapDocument doc, string dir)
    {
        ArgumentNullException.ThrowIfNull(doc);
        ArgumentException.ThrowIfNullOrEmpty(dir);
        Directory.CreateDirectory(dir);
        File.WriteAllText(Path.Combine(dir, ManifestSection), SerializeManifest(doc), Utf8NoBom);
        File.WriteAllText(Path.Combine(dir, GeometrySection), SerializeGeometry(doc), Utf8NoBom);
        File.WriteAllText(Path.Combine(dir, EntitiesSection), SerializeEntities(doc), Utf8NoBom);
    }

    /// <summary>Write the package as a single zip file (the shipping layout).</summary>
    public static void WriteToZip(VmapDocument doc, string path)
    {
        ArgumentNullException.ThrowIfNull(doc);
        ArgumentException.ThrowIfNullOrEmpty(path);
        string? parent = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(parent))
            Directory.CreateDirectory(parent);
        using FileStream fs = File.Create(path);
        using var archive = new ZipArchive(fs, ZipArchiveMode.Create);
        WriteZipEntry(archive, ManifestSection, SerializeManifest(doc));
        WriteZipEntry(archive, GeometrySection, SerializeGeometry(doc));
        WriteZipEntry(archive, EntitiesSection, SerializeEntities(doc));
    }

    private static readonly UTF8Encoding Utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);

    private static void WriteZipEntry(ZipArchive archive, string name, string content)
    {
        ZipArchiveEntry entry = archive.CreateEntry(name, CompressionLevel.Optimal);
        using Stream s = entry.Open();
        using var writer = new StreamWriter(s, Utf8NoBom);
        writer.Write(content);
    }

    private static string SerializeManifest(VmapDocument doc)
        => JsonSerializer.Serialize(new ManifestDto
        {
            FormatVersion = VmapDocument.CurrentFormatVersion,
            Name = doc.Manifest.Name,
            Title = doc.Manifest.Title,
            SourceKind = doc.Manifest.SourceKind,
            SourcePath = doc.Manifest.SourcePath,
            SourceHash = doc.Manifest.SourceHash,
        }, JsonOptions);

    private static string SerializeGeometry(VmapDocument doc)
    {
        var geo = new GeometryDto
        {
            Brushes = new BrushDto[doc.Brushes.Count],
            Patches = new PatchDto[doc.Patches.Count],
        };

        for (int i = 0; i < doc.Brushes.Count; i++)
        {
            VmapBrush b = doc.Brushes[i];
            var faces = new FaceDto[b.Faces.Count];
            for (int f = 0; f < b.Faces.Count; f++)
            {
                VmapFace face = b.Faces[f];
                faces[f] = new FaceDto
                {
                    Normal = Arr(face.Plane.Normal),
                    Dist = face.Plane.Dist,
                    Material = face.Material,
                    AxisU = Arr(face.Projection.AxisU),
                    AxisV = Arr(face.Projection.AxisV),
                    OffsetU = face.Projection.OffsetU,
                    OffsetV = face.Projection.OffsetV,
                    Surface = face.SurfaceFlags,
                    Contents = face.ContentFlags,
                };
            }
            geo.Brushes[i] = new BrushDto
            {
                Id = b.Id,
                Detail = b.IsDetail,
                Contents = b.ContentFlags,
                Faces = faces,
            };
        }

        for (int i = 0; i < doc.Patches.Count; i++)
        {
            VmapPatch p = doc.Patches[i];
            var ctrl = new float[p.Controls.Count * 3];
            for (int c = 0; c < p.Controls.Count; c++)
            {
                ctrl[c * 3 + 0] = p.Controls[c].X;
                ctrl[c * 3 + 1] = p.Controls[c].Y;
                ctrl[c * 3 + 2] = p.Controls[c].Z;
            }
            var uvs = new float[p.ControlUvs.Count * 2];
            for (int c = 0; c < p.ControlUvs.Count; c++)
            {
                uvs[c * 2 + 0] = p.ControlUvs[c].X;
                uvs[c * 2 + 1] = p.ControlUvs[c].Y;
            }
            geo.Patches[i] = new PatchDto
            {
                Id = p.Id,
                Material = p.Material,
                Width = p.Width,
                Height = p.Height,
                Surface = p.SurfaceFlags,
                Contents = p.ContentFlags,
                Controls = ctrl,
                Uvs = uvs,
            };
        }

        return JsonSerializer.Serialize(geo, JsonOptions);
    }

    private static string SerializeEntities(VmapDocument doc)
    {
        var dto = new EntitiesDto { Entities = new EntityDto[doc.Entities.Count] };
        for (int i = 0; i < doc.Entities.Count; i++)
        {
            VmapEntity e = doc.Entities[i];

            // Deterministic key order so unchanged data round-trips byte-identically (§11.8 diff-friendliness).
            var fields = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (string key in e.Fields.Keys.OrderBy(k => k, StringComparer.Ordinal))
                fields[key] = e.Fields[key];

            dto.Entities[i] = new EntityDto
            {
                Id = e.Id,
                ClassName = e.ClassName,
                Fields = fields,
                Brushes = e.BrushIds.ToArray(),
                Patches = e.PatchIds.ToArray(),
            };
        }
        return JsonSerializer.Serialize(dto, JsonOptions);
    }

    private static float[] Arr(Vector3 v) => new[] { v.X, v.Y, v.Z };

    /// <summary>
    /// Content hash of arbitrary source bytes (FNV-1a 64), used to stamp <see cref="VmapManifest.SourceHash"/>
    /// so a bake cache can be keyed to the geometry it was built from and a redundant re-import is detectable.
    /// Not cryptographic — it only has to notice that bytes changed.
    /// </summary>
    public static string HashBytes(ReadOnlySpan<byte> data)
    {
        const ulong offset = 14695981039346656037UL;
        const ulong prime = 1099511628211UL;
        ulong h = offset;
        foreach (byte b in data)
        {
            h ^= b;
            h *= prime;
        }
        return h.ToString("x16", CultureInfo.InvariantCulture);
    }

    // =============================================================================================
    //  On-disk DTOs — the wire shape, deliberately decoupled from the domain model so refactoring
    //  VmapDocument does not silently change the file format. Property order here IS the file order.
    // =============================================================================================

    private sealed class ManifestDto
    {
        [JsonPropertyName("formatVersion")] public int FormatVersion { get; set; }
        [JsonPropertyName("name")] public string? Name { get; set; }
        [JsonPropertyName("title")] public string? Title { get; set; }
        [JsonPropertyName("sourceKind")] public string? SourceKind { get; set; }
        [JsonPropertyName("sourcePath")] public string? SourcePath { get; set; }
        [JsonPropertyName("sourceHash")] public string? SourceHash { get; set; }
    }

    private sealed class GeometryDto
    {
        [JsonPropertyName("brushes")] public BrushDto[]? Brushes { get; set; }
        [JsonPropertyName("patches")] public PatchDto[]? Patches { get; set; }
    }

    private sealed class BrushDto
    {
        [JsonPropertyName("id")] public int Id { get; set; }
        [JsonPropertyName("detail")] public bool Detail { get; set; }
        [JsonPropertyName("contents")] public int Contents { get; set; }
        [JsonPropertyName("faces")] public FaceDto[]? Faces { get; set; }
    }

    private sealed class FaceDto
    {
        [JsonPropertyName("normal")] public float[]? Normal { get; set; }
        [JsonPropertyName("dist")] public float Dist { get; set; }
        [JsonPropertyName("material")] public string? Material { get; set; }
        [JsonPropertyName("axisU")] public float[]? AxisU { get; set; }
        [JsonPropertyName("axisV")] public float[]? AxisV { get; set; }
        [JsonPropertyName("offsetU")] public float OffsetU { get; set; }
        [JsonPropertyName("offsetV")] public float OffsetV { get; set; }
        [JsonPropertyName("surface")] public int Surface { get; set; }
        [JsonPropertyName("contents")] public int Contents { get; set; }
    }

    private sealed class PatchDto
    {
        [JsonPropertyName("id")] public int Id { get; set; }
        [JsonPropertyName("material")] public string? Material { get; set; }
        [JsonPropertyName("width")] public int Width { get; set; }
        [JsonPropertyName("height")] public int Height { get; set; }
        [JsonPropertyName("surface")] public int Surface { get; set; }
        [JsonPropertyName("contents")] public int Contents { get; set; }
        [JsonPropertyName("controls")] public float[]? Controls { get; set; }
        [JsonPropertyName("uvs")] public float[]? Uvs { get; set; }
    }

    private sealed class EntitiesDto
    {
        [JsonPropertyName("entities")] public EntityDto[]? Entities { get; set; }
    }

    private sealed class EntityDto
    {
        [JsonPropertyName("id")] public int Id { get; set; }
        [JsonPropertyName("classname")] public string? ClassName { get; set; }
        [JsonPropertyName("fields")] public Dictionary<string, string>? Fields { get; set; }
        [JsonPropertyName("brushes")] public int[]? Brushes { get; set; }
        [JsonPropertyName("patches")] public int[]? Patches { get; set; }
    }
}
