// Port of Base/darkplaces/svvm_cmds.c vm_sv_extensions[] (which csprogs.c CL_VM_Init also gives the
// client program) and the conditions of prvm_cmds.c checkextension. The list is generated from the C.
namespace VortexArena.Legacy.Csqc;

/// <summary>
/// The extension names DarkPlaces answers true for in checkextension. Three are left out because their
/// answer in the C depends on a library this client does not have: DP_CRYPTO and DP_QC_DIGEST_SHA256
/// (d0_blind_id) and DP_PHYSICS_ODE (ODE). The two whose answer is "is libcurl there" are in
/// <see cref="Http"/>: the host adds them when the program has an HTTP client (CsqcHostOptions.UriRequests).
/// </summary>
public static class CsqcExtensions
{
    /// <summary>checkextension's "special shreck for libcurl": true only while HTTP requests can be made.</summary>
    public static readonly string[] Http = { "DP_QC_URI_GET", "DP_QC_URI_POST" };

    public static readonly string[] All =
    {
        "BX_WAL_SUPPORT", "DP_BUTTONCHAT", "DP_BUTTONUSE", "DP_CL_LOADSKY", "DP_CON_ALIASPARAMETERS",
        "DP_CON_BESTWEAPON", "DP_CON_EXPANDCVAR", "DP_CON_SET", "DP_CON_SETA", "DP_CON_STARTMAP", "DP_COVERAGE",
        "DP_CSQC_BINDMAPS", "DP_CSQC_ENTITYWORLDOBJECT", "DP_CSQC_ENTITYMODELLIGHT",
        "DP_CSQC_ENTITYTRANSPARENTSORTING_OFFSET", "DP_CSQC_MAINVIEW", "DP_CSQC_MINFPS_QUALITY",
        "DP_CSQC_MULTIFRAME_INTERPOLATION", "DP_CSQC_BOXPARTICLES", "DP_CSQC_SPAWNPARTICLE",
        "DP_CSQC_QUERYRENDERENTITY", "DP_CSQC_ROTATEMOVES", "DP_CSQC_SETPAUSE", "DP_CSQC_V_CALCREFDEF_WIP1",
        "DP_CSQC_V_CALCREFDEF_WIP2", "DP_EF_ADDITIVE", "DP_EF_BLUE", "DP_EF_DOUBLESIDED", "DP_EF_DYNAMICMODELLIGHT",
        "DP_EF_FLAME", "DP_EF_FULLBRIGHT", "DP_EF_NODEPTHTEST", "DP_EF_NODRAW", "DP_EF_NOGUNBOB",
        "DP_EF_NOSELFSHADOW", "DP_EF_NOSHADOW", "DP_EF_RED", "DP_EF_RESTARTANIM_BIT", "DP_EF_STARDUST",
        "DP_EF_TELEPORT_BIT", "DP_ENT_ALPHA", "DP_ENT_COLORMOD", "DP_ENT_CUSTOMCOLORMAP",
        "DP_ENT_EXTERIORMODELTOCLIENT", "DP_ENT_GLOW", "DP_ENT_GLOWMOD", "DP_ENT_LOWPRECISION", "DP_ENT_SCALE",
        "DP_ENT_TRAILEFFECTNUM", "DP_ENT_VIEWMODEL", "DP_GFX_EXTERNALTEXTURES", "DP_GFX_EXTERNALTEXTURES_PERMAP",
        "DP_GFX_FOG", "DP_GFX_MODEL_INTERPOLATION", "DP_GFX_QUAKE3MODELTAGS", "DP_GFX_SKINFILES", "DP_GFX_SKYBOX",
        "DP_GFX_FONTS", "DP_GFX_FONTS_FREETYPE", "DP_UTF8", "DP_FONT_VARIABLEWIDTH", "DP_HALFLIFE_MAP",
        "DP_HALFLIFE_MAP_CVAR", "DP_HALFLIFE_SPRITE", "DP_INPUTBUTTONS", "DP_LIGHTSTYLE_STATICVALUE",
        "DP_LITSPRITES", "DP_LITSUPPORT", "DP_MONSTERWALK", "DP_MOVETYPEBOUNCEMISSILE", "DP_MOVETYPEFLYWORLDONLY",
        "DP_MOVETYPEFOLLOW", "DP_NULL_MODEL", "DP_QC_ASINACOSATANATAN2TAN", "DP_QC_AUTOCVARS", "DP_QC_CHANGEPITCH",
        "DP_QC_CMD", "DP_QC_COPYENTITY", "DP_QC_CRC16", "DP_QC_CVAR_DEFSTRING", "DP_QC_CVAR_DESCRIPTION",
        "DP_QC_CVAR_STRING", "DP_QC_CVAR_TYPE", "DP_QC_DIGEST", "DP_QC_EDICT_NUM", "DP_QC_ENTITYDATA",
        "DP_QC_ENTITYSTRING", "DP_QC_ETOS", "DP_QC_EXTRESPONSEPACKET", "DP_QC_FINDBOX", "DP_QC_FINDCHAIN",
        "DP_QC_FINDCHAINFLAGS", "DP_QC_FINDCHAINFLOAT", "DP_QC_FINDCHAIN_TOFIELD", "DP_QC_FINDFLAGS",
        "DP_QC_FINDFLOAT", "DP_QC_FS_SEARCH", "DP_QC_FS_SEARCH_PACKFILE", "DP_QC_GETLIGHT", "DP_QC_GETSURFACE",
        "DP_QC_GETSURFACETRIANGLE", "DP_QC_GETSURFACEPOINTATTRIBUTE", "DP_QC_GETTAGINFO",
        "DP_QC_GETTAGINFO_BONEPROPERTIES", "DP_QC_GETTIME", "DP_QC_GETTIME_CDTRACK", "DP_QC_I18N", "DP_QC_LOG",
        "DP_QC_MINMAXBOUND", "DP_QC_MULTIPLETEMPSTRINGS", "DP_QC_NUDGEOUTOFSOLID", "DP_QC_NUM_FOR_EDICT",
        "DP_QC_RANDOMVEC", "DP_QC_SINCOSSQRTPOW", "DP_QC_SPRINTF", "DP_QC_STRFTIME", "DP_QC_STRINGBUFFERS",
        "DP_QC_STRINGBUFFERS_CVARLIST", "DP_QC_STRINGBUFFERS_EXT_WIP", "DP_QC_STRINGCOLORFUNCTIONS",
        "DP_QC_STRING_CASE_FUNCTIONS", "DP_QC_STRREPLACE", "DP_QC_TOKENIZEBYSEPARATOR", "DP_QC_TOKENIZE_CONSOLE",
        "DP_QC_TRACEBOX", "DP_QC_TRACETOSS", "DP_QC_TRACE_MOVETYPE_HITMODEL", "DP_QC_TRACE_MOVETYPE_WORLDONLY",
        "DP_QC_UNLIMITEDTEMPSTRINGS", "DP_QC_URI_ESCAPE", "DP_QC_VECTOANGLES_WITH_ROLL", "DP_QC_VECTORVECTORS",
        "DP_QC_WHICHPACK", "DP_QUAKE2_MODEL", "DP_QUAKE2_SPRITE", "DP_QUAKE3_MAP", "DP_QUAKE3_MODEL",
        "DP_REGISTERCVAR", "DP_SKELETONOBJECTS", "DP_SND_DIRECTIONLESSATTNNONE", "DP_SND_FAKETRACKS",
        "DP_SND_SOUND7_WIP1", "DP_SND_SOUND7_WIP2", "DP_SND_OGGVORBIS", "DP_SND_SETPARAMS", "DP_SND_STEREOWAV",
        "DP_SND_GETSOUNDTIME", "DP_VIDEO_DPV", "DP_VIDEO_SUBTITLES", "DP_SOLIDCORPSE", "DP_SPRITE32",
        "DP_SV_BOTCLIENT", "DP_SV_BOUNCEFACTOR", "DP_SV_CLIENTCAMERA", "DP_SV_CLIENTCOLORS", "DP_SV_CLIENTNAME",
        "DP_SV_CMD", "DP_SV_CUSTOMIZEENTITYFORCLIENT", "DP_SV_DISABLECLIENTPREDICTION", "DP_SV_DISCARDABLEDEMO",
        "DP_SV_DRAWONLYTOCLIENT", "DP_SV_DROPCLIENT", "DP_SV_EFFECT", "DP_SV_ENTITYCONTENTSTRANSITION",
        "DP_SV_MODELFLAGS_AS_EFFECTS", "DP_SV_MOVETYPESTEP_LANDEVENT", "DP_SV_NETADDRESS", "DP_SV_NODRAWTOCLIENT",
        "DP_SV_ONENTITYNOSPAWNFUNCTION", "DP_SV_ONENTITYPREPOSTSPAWNFUNCTION", "DP_SV_PING", "DP_SV_PING_PACKETLOSS",
        "DP_SV_PLAYERPHYSICS", "DP_SV_POINTPARTICLES", "DP_SV_POINTSOUND", "DP_SV_PRECACHEANYTIME", "DP_SV_PRINT",
        "DP_SV_PUNCHVECTOR", "DP_SV_QCSTATUS", "DP_SV_ROTATINGBMODEL", "DP_SV_SETCOLOR", "DP_SV_SHUTDOWN",
        "DP_SV_SLOWMO", "DP_SV_SPAWNFUNC_PREFIX", "DP_SV_WRITEPICTURE", "DP_SV_WRITEUNTERMINATEDSTRING",
        "DP_TE_BLOOD", "DP_TE_BLOODSHOWER", "DP_TE_CUSTOMFLASH", "DP_TE_EXPLOSIONRGB", "DP_TE_FLAMEJET",
        "DP_TE_PARTICLECUBE", "DP_TE_PARTICLERAIN", "DP_TE_PARTICLESNOW", "DP_TE_PLASMABURN", "DP_TE_QUADEFFECTS1",
        "DP_TE_SMALLFLASH", "DP_TE_SPARK", "DP_TE_STANDARDEFFECTBUILTINS",
        // svvm_cmds.c:216 lacks a comma, so C joins these two names into one string and DarkPlaces answers
        // false for either on its own. Kept as the C has it.
        "DP_TRACE_HITCONTENTSMASK_SURFACEINFODP_USERMOVETYPES",
        "DP_VIEWZOOM", "EXT_BITSHIFT", "FRIK_FILE", "FTE_CSQC_SKELETONOBJECTS",
        "FTE_QC_CHECKPVS", "FTE_STRINGS", "KRIMZON_SV_PARSECLIENTCOMMAND", "NEH_CMD_PLAY2", "NEH_RESTOREGAME",
        "NEXUIZ_PLAYERMODEL", "NXQ_GFX_LETTERBOX", "PRYDON_CLIENTCURSOR", "TENEBRAE_GFX_DLIGHTS",
        "TW_SV_STEPCONTROL", "ZQ_PAUSE", "DP_RM_CLIPGROUP",
    };
}
